plugins {
    id 'groovy'
    id 'java-gradle-plugin'
    id 'maven-publish'
}


group = 'org.example'
version = '1.0.0'
description = 'schemaInjectionplugin'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.github.javaparser:javaparser-core:3.25.8'
    implementation 'org.apache.commons:commons-text:1.11.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.16.1'
}
gradlePlugin {
    plugins {
        openapiSchemaInjector {
            id = 'com.example.openapi-schema-injector'
            implementationClass = 'org.example.schemainjectionplugin.OpenApiSchemaInjectorPlugin'
        }
    }
}
